{
  "openapi": "3.0.1",
  "info": {
    "title": "Local Test",
    "description": "Manage pets, orders, purchases, users, and other operations in the pet shop.",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "Pet"
    },
    {
      "name": "pet"
    },
    {
      "name": "Store"
    },
    {
      "name": "Payments"
    },
    {
      "name": "store"
    },
    {
      "name": "User"
    },
    {
      "name": "user"
    }
  ],
  "paths": {
    "/pets/{id}": {
      "get": {
        "summary": "Get a pet",
        "deprecated": false,
        "description": "Returns a single pet by its unique ID.",
        "operationId": "getPetById",
        "tags": [
          "Pet",
          "pet"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The unique identifier of the pet.",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "id": 100,
                  "category": {
                    "id": 101,
                    "name": "dog"
                  },
                  "name": "Luna",
                  "photoUrls": [
                    "https://loremflickr.com/400/400?lock=2557291284045546",
                    "https://loremflickr.com/400/400?lock=1603075073377479"
                  ],
                  "tags": [
                    {
                      "id": 15,
                      "name": "Dalmatian"
                    }
                  ],
                  "status": "available"
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "put": {
        "summary": "Update a pet",
        "deprecated": false,
        "description": "Update the details of an existing pet.",
        "operationId": "updatePet",
        "tags": [
          "Pet",
          "pet"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The unique identifier of the pet.",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Pet updated successfully.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "id": 57619952,
                  "category": {
                    "id": 97056790,
                    "name": "Mona Kshlerin"
                  },
                  "name": "doggie",
                  "photoUrls": [
                    "https://loremflickr.com/400/400?lock=190427740691304",
                    "https://loremflickr.com/400/400?lock=5512522463237719",
                    "https://loremflickr.com/400/400?lock=1184069713463914"
                  ],
                  "tags": [
                    {
                      "id": 1230446,
                      "name": "Timmy Schiller"
                    },
                    {
                      "id": 310656,
                      "name": "Ricardo Emard PhD"
                    }
                  ],
                  "status": "pending"
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "delete": {
        "summary": "Delete a pet",
        "deprecated": false,
        "description": "Delete a pet by its unique ID.",
        "operationId": "deletePet",
        "tags": [
          "Pet",
          "pet"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The unique identifier of the pet.",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "api_key",
            "in": "header",
            "description": "API key for authorization, if required.",
            "required": false,
            "example": "apikey-xxxxx",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Pet deleted successfully.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/pets": {
      "post": {
        "summary": "Create a pet",
        "deprecated": false,
        "description": "Add a new pet to the store.",
        "operationId": "addPet",
        "tags": [
          "Pet",
          "pet"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "category": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "name": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "id",
                      "name"
                    ]
                  },
                  "name": {
                    "type": "string"
                  },
                  "photoUrls": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "tags": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "name": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "id",
                        "name"
                      ]
                    }
                  },
                  "status": {
                    "type": "string"
                  }
                },
                "required": [
                  "id",
                  "category",
                  "name",
                  "photoUrls",
                  "tags",
                  "status"
                ]
              },
              "example": {
                "id": 83,
                "category": {
                  "id": 19,
                  "name": "Jill Ryan V"
                },
                "name": "doggie",
                "photoUrls": [
                  "https://loremflickr.com/400/400?lock=5113434361460619",
                  "https://loremflickr.com/400/400?lock=2628258536296497",
                  "https://loremflickr.com/400/400?lock=8705164908685543"
                ],
                "tags": [
                  {
                    "id": 25,
                    "name": "Troy Harber"
                  },
                  {
                    "id": 25,
                    "name": "Richard Hirthe-Langosh"
                  },
                  {
                    "id": 10,
                    "name": "Ernestine Pollich"
                  }
                ],
                "status": "sold"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Pet created successfully.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer",
                      "description": "The unique identifier for the pet."
                    }
                  },
                  "required": [
                    "id"
                  ]
                },
                "example": {
                  "id": 100
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "get": {
        "summary": "List pets",
        "deprecated": false,
        "description": "Multiple status values can be provided with comma separated strings.",
        "operationId": "findPetsByStatus",
        "tags": [
          "Pet",
          "pet"
        ],
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "description": "Status values to filter pets by (comma separated values are accepted).",
            "required": false,
            "example": [
              "available,pending"
            ],
            "schema": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "available",
                  "pending",
                  "sold"
                ],
                "default": "available"
              }
            }
          },
          {
            "name": "tags",
            "in": "query",
            "description": "Filter results by tags (comma separated or repeated parameters).",
            "required": false,
            "example": [
              "dog,fish"
            ],
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {}
                  }
                },
                "examples": {
                  "1": {
                    "summary": "Success",
                    "value": {
                      "id": 15,
                      "category": {
                        "id": 21,
                        "name": "Marcella Weissnat"
                      },
                      "name": "doggie",
                      "photoUrls": [
                        "https://loremflickr.com/400/400?lock=3918785348234384",
                        "https://loremflickr.com/400/400?lock=6202587563304484"
                      ],
                      "tags": [
                        {
                          "id": 47,
                          "name": "Celia Breitenberg"
                        }
                      ],
                      "status": "available"
                    }
                  },
                  "2": {
                    "summary": "Success",
                    "value": {
                      "id": 71,
                      "category": {
                        "id": 46,
                        "name": "Amber Boyer"
                      },
                      "name": "doggie",
                      "photoUrls": [
                        "https://loremflickr.com/400/400?lock=2842023516272171"
                      ],
                      "tags": [
                        {
                          "id": 11,
                          "name": "Dr. Victoria Zieme"
                        }
                      ],
                      "status": "pending"
                    }
                  },
                  "3": {
                    "summary": "Success",
                    "value": {
                      "id": 40,
                      "category": {
                        "id": 61,
                        "name": "Sheryl Boyer"
                      },
                      "name": "doggie",
                      "photoUrls": [
                        "https://loremflickr.com/400/400?lock=5750598354305884",
                        "https://loremflickr.com/400/400?lock=2063547589454977"
                      ],
                      "tags": [
                        {
                          "id": 78,
                          "name": "Gene Deckow-Lynch"
                        }
                      ],
                      "status": "available"
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/pets/{petId}/images": {
      "post": {
        "summary": "Upload a pet image",
        "deprecated": false,
        "description": "Upload an image for the specified pet.",
        "operationId": "uploadFile",
        "tags": [
          "Pet",
          "pet"
        ],
        "parameters": [
          {
            "name": "petId",
            "in": "path",
            "description": "",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file": {
                    "description": "File to upload",
                    "type": "string",
                    "format": "binary",
                    "example": ""
                  }
                },
                "required": [
                  "file"
                ]
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "code": 3,
                  "type": "ex dolor",
                  "message": "Pecus carcer cometes credo."
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/orders/{orderId}/payment": {
      "post": {
        "summary": "Pay for an Order",
        "deprecated": false,
        "description": "A payment is an attempt to pay for the order, which will confirm it for the user and enable them to get their tickets.",
        "operationId": "create-order-payment",
        "tags": [
          "Store",
          "Payments"
        ],
        "parameters": [
          {
            "name": "orderId",
            "in": "path",
            "description": "",
            "required": true,
            "example": "123456",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "examples": {
                "Card": {
                  "value": {
                    "amount": 49.99,
                    "currency": "gbp",
                    "source": {
                      "object": "card",
                      "name": "J. Doe",
                      "number": "4242424242424242",
                      "cvc": "123",
                      "exp_month": 12,
                      "exp_year": 2025,
                      "address_line1": "123 Fake Street",
                      "address_line2": "4th Floor",
                      "address_city": "London",
                      "address_country": "gb",
                      "address_post_code": "N12 9XX"
                    }
                  },
                  "summary": "Card Payment"
                },
                "Bank": {
                  "value": {
                    "amount": 100.5,
                    "currency": "gbp",
                    "source": {
                      "object": "bank_account",
                      "name": "J. Doe",
                      "number": "00012345",
                      "sort_code": "000123",
                      "account_type": "individual",
                      "bank_name": "Starling Bank",
                      "country": "gb"
                    }
                  },
                  "summary": "Bank Account Payment"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Payment successful",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "type": "object",
                      "properties": {}
                    },
                    {
                      "type": "object",
                      "properties": {
                        "links": {
                          "type": "object",
                          "properties": {}
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "Card Payment",
                    "value": {
                      "id": "2e3b4f5a-6b7c-8d9e-0f1a-2b3c4d5e6f7a",
                      "amount": 49.99,
                      "currency": "gbp",
                      "source": {
                        "object": "card",
                        "name": "J. Doe",
                        "number": "************4242",
                        "cvc": "123",
                        "exp_month": 12,
                        "exp_year": 2025,
                        "address_country": "gb",
                        "address_post_code": "N12 9XX"
                      },
                      "status": "succeeded",
                      "links": {
                        "order": "https://api.example.com/orders/1725ff48-ab45-4bb5-9d02-88745177dedb/payment"
                      }
                    }
                  },
                  "2": {
                    "summary": "Bank Account Payment",
                    "value": {
                      "id": "2e3b4f5a-6b7c-8d9e-0f1a-2b3c4d5e6f7a",
                      "amount": 100.5,
                      "currency": "gbp",
                      "source": {
                        "object": "bank_account",
                        "name": "J. Doe",
                        "account_type": "individual",
                        "number": "*********2345",
                        "sort_code": "000123",
                        "bank_name": "Starling Bank",
                        "country": "gb"
                      },
                      "status": "succeeded",
                      "links": {
                        "order": "https://api.example.com/orders/1725ff48-ab45-4bb5-9d02-88745177dedb"
                      }
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/inventories": {
      "get": {
        "summary": "List all inventories",
        "deprecated": false,
        "description": "Returns a map of status codes to quantities.",
        "operationId": "getInventory",
        "tags": [
          "Store",
          "store"
        ],
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "description": "Status values to filter inventory by (comma separated).",
            "required": false,
            "example": [
              "available, pending"
            ],
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "integer",
                    "format": "int32"
                  },
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/orders": {
      "post": {
        "summary": "Create an order",
        "deprecated": false,
        "description": "Place a new order in the store.",
        "operationId": "placeOrder",
        "tags": [
          "Store",
          "store"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "id": 44524671,
                  "petId": 90180021,
                  "quantity": 23,
                  "shipDate": "2025-08-15",
                  "status": "placed",
                  "complete": false
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/orders/{id}": {
      "get": {
        "summary": "Get an order",
        "deprecated": false,
        "description": "For valid response try integer IDs with value >= 1 and <= 10. Other values will generate exceptions.",
        "operationId": "getOrderById",
        "tags": [
          "Store",
          "store"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The unique identifier for the order.",
            "required": true,
            "example": "123",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "id": 40238436,
                  "petId": 69923630,
                  "quantity": 87,
                  "shipDate": "2024-12-09",
                  "status": "approved",
                  "complete": false
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "delete": {
        "summary": "Delete an order",
        "deprecated": false,
        "description": "For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors.",
        "operationId": "deleteOrder",
        "tags": [
          "Store",
          "store"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The unique identifier for the order.",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Order deleted successfully.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users": {
      "post": {
        "summary": "Create a user",
        "deprecated": false,
        "description": "Create a new user in the system.",
        "operationId": "createUser",
        "tags": [
          "User",
          "user"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "username": "Kyle Kihn",
                "firstName": "Cade",
                "lastName": "Borer",
                "email": "Lilyan3@gmail.com",
                "password": "YFVfBo7nd2Dgh0b",
                "phone": "(863) 898-2053",
                "userStatus": 1
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User created successfully.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/{username}": {
      "put": {
        "summary": "Update a user",
        "deprecated": false,
        "description": "This can only be done by the logged in user.",
        "operationId": "updateUser",
        "tags": [
          "User",
          "user"
        ],
        "parameters": [
          {
            "name": "username",
            "in": "path",
            "description": "The username.",
            "required": true,
            "example": "johndoe",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "id": 51,
                "username": "Norma Ritchie",
                "firstName": "Jeffrey",
                "lastName": "Kris",
                "email": "Victoria.Kozey59@yahoo.com",
                "password": "xwrQ4gkAA1SQFmd",
                "phone": "(863) 406-3542",
                "userStatus": -1
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User updated successfully.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "get": {
        "summary": "Get a user",
        "deprecated": false,
        "description": "Retrieve a user by username.",
        "operationId": "getUserByName",
        "tags": [
          "User",
          "user"
        ],
        "parameters": [
          {
            "name": "username",
            "in": "path",
            "description": "The username.",
            "required": true,
            "example": "johndoe",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "id": 99,
                  "username": "Mr. Guadalupe Bailey",
                  "firstName": "Amelie",
                  "lastName": "Hackett",
                  "email": "Murphy26@gmail.com",
                  "phone": "(632) 437-7270",
                  "userStatus": 0
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "delete": {
        "summary": "Delete a user",
        "deprecated": false,
        "description": "This can only be done by the logged in user.",
        "operationId": "deleteUser",
        "tags": [
          "User",
          "user"
        ],
        "parameters": [
          {
            "name": "username",
            "in": "path",
            "description": "The username.",
            "required": true,
            "example": "johndoe",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User deleted successfully.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/login": {
      "get": {
        "summary": "Login",
        "deprecated": false,
        "description": "Log in a user and generate a session.",
        "operationId": "loginUser",
        "tags": [
          "User",
          "user"
        ],
        "parameters": [
          {
            "name": "username",
            "in": "query",
            "description": "The username for login.",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "password",
            "in": "query",
            "description": "The password for login in clear text.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            },
            "headers": {
              "X-Expires-After": {
                "required": false,
                "description": "date in UTC when token expires",
                "schema": {
                  "type": "string",
                  "format": "date-time"
                }
              },
              "X-Rate-Limit": {
                "required": false,
                "description": "calls per hour allowed by the user",
                "schema": {
                  "type": "integer",
                  "format": "int32"
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/logout": {
      "get": {
        "summary": "Logout",
        "deprecated": false,
        "description": "Logout the currently logged in user.",
        "operationId": "logoutUser",
        "tags": [
          "User",
          "user"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "responses": {},
    "securitySchemes": {}
  },
  "servers": [],
  "security": []
}